# To regenerate the NeuroML parser after modifying neurokernel.xsd, run make in
# this directory.

all:
	generateDS.py -o nml.py --use-getter-setter=none --silence --user-methods=helper_methods neurokernel.xsd

